language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
script:
- python test/tests.py
notifications:
  slack:
    secure: HQnlkzjvqTICI6Lm680nbcwxAPCFd2ptkmvjPqzS/2fNaL6IpmsYZCJ9BmVH4tLdFovNWhMPj549lq78lOrIOgATkFRhiBuKhVgwpTrL12zEJ5s6rxqHhcQUnrUu/84uyD4/Wa3xXtqb7yOX+CyZRMPJA5mukI5sB/mvnas6DcjOTfNyGzfd7ONfDzaG1CgqSyGYaXfH9dXnsoHqvD+56qk95f8YwMkLVMUZLhiKU5M57HV3/s2fjRQbm7V2Xec96b24jh8vKtPSYU8jNP+3tUNFm2Eybd+rd7MulQS1jcx68bodG8SCO34DCR+twk0FKtvkTPRINKBGkWbnU9/QKrP4KHi5nBF8EYFYtyBFtQlStwFuk5C+5YJYQvcOqG4+qqdjG7WNrDDLnbx7Pq30qMCC6QYn2bRD2hqOIF3m/olCaE5mDLS3aGN2zDc9jRGf49Lj7qTVm9XBG+mkZNl4RGjCn/y8Z6tNfCxxs2guUxega4+SSFmQF3HSJlJBohxZidT4lBmlovr5OKIncCM3Rl2IKjhYxAOuFVs+209zQBKVGJihDukCxtWO+fCzLDlDll2eOUVwUXNjm4BIRw2h5kIne/5yLhAhvoy2Lny0NJpktAEP8J58Y+42p9S6IfZkiZfYZP+RwICOQRxdRptme/+TPu70HYeHJR+azBgTRGU=
