language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install .
script:
- python test/tests.py
notifications:
  slack:
    secure: HQnlkzjvqTICI6Lm680nbcwxAPCFd2ptkmvjPqzS/2fNaL6IpmsYZCJ9BmVH4tLdFovNWhMPj549lq78lOrIOgATkFRhiBuKhVgwpTrL12zEJ5s6rxqHhcQUnrUu/84uyD4/Wa3xXtqb7yOX+CyZRMPJA5mukI5sB/mvnas6DcjOTfNyGzfd7ONfDzaG1CgqSyGYaXfH9dXnsoHqvD+56qk95f8YwMkLVMUZLhiKU5M57HV3/s2fjRQbm7V2Xec96b24jh8vKtPSYU8jNP+3tUNFm2Eybd+rd7MulQS1jcx68bodG8SCO34DCR+twk0FKtvkTPRINKBGkWbnU9/QKrP4KHi5nBF8EYFYtyBFtQlStwFuk5C+5YJYQvcOqG4+qqdjG7WNrDDLnbx7Pq30qMCC6QYn2bRD2hqOIF3m/olCaE5mDLS3aGN2zDc9jRGf49Lj7qTVm9XBG+mkZNl4RGjCn/y8Z6tNfCxxs2guUxega4+SSFmQF3HSJlJBohxZidT4lBmlovr5OKIncCM3Rl2IKjhYxAOuFVs+209zQBKVGJihDukCxtWO+fCzLDlDll2eOUVwUXNjm4BIRw2h5kIne/5yLhAhvoy2Lny0NJpktAEP8J58Y+42p9S6IfZkiZfYZP+RwICOQRxdRptme/+TPu70HYeHJR+azBgTRGU=
deploy:
  provider: pypi
  user: thesoulshell
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.6
  password:
    secure: cGOVFe+hfJhnd5BcrvJcUvYsVqyd/b+LN3BB7QyRcLijabikONbh4+YT1oCaJtSQzI6uJYSPGSRDPLlYoV3PnnWZqaOYyUwbcGJIkfJrS85eHsws1ARoZoyegx5zfqrwUp/xOMgz/VVw0JWNzzIuDD6Wuf5Xh4GyX52vBfl0LlpuQV6M8rryBkCboKUeuAOrabPUhSk42xj9TeGh81tvOEcJimlzgYtUb131FbeQC6t75W5Ix8OOHhYZbvM++TCNL+NJ/q0i1oGJbi7BeJ68p9S5JiDMyLN8AQo89O87UqCcTU+WmUtqUIronRUUwREqWrQjevPxcH4mobUs5tu15Oyxt7hlvG1sUAB/jCV7jQXorumo5JGcts3UistOV55OSFtO647xG+23iSGNn2YZiC21/LYeTDVmPT4XO51O8zxU7O4EkiH290wA6Jnnaqykb89c+1HfyY3MYc++975wQBZJquRl2/tIHnTgWdUT7ayD2wStPu6+Vhj5gaoAIdKfBiECQ5MAPgksBT7RcQbLpx/CDzOxbIQ2d2SnjnZ7FCzZvhknmIgUsZe3304LBIkCVE9ayVwltLuJWWNUkLB/23DdAJ0fR13uNXtqjDjF23Zm9OLdACXCvHjwenLo1rUJSCdsiRwJL8TsPRehMI9ErOUMsE2sh3o3wdzvY8wO7MA=
