language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install .
script:
- python test/tests.py
notifications:
  slack:
    secure: HQnlkzjvqTICI6Lm680nbcwxAPCFd2ptkmvjPqzS/2fNaL6IpmsYZCJ9BmVH4tLdFovNWhMPj549lq78lOrIOgATkFRhiBuKhVgwpTrL12zEJ5s6rxqHhcQUnrUu/84uyD4/Wa3xXtqb7yOX+CyZRMPJA5mukI5sB/mvnas6DcjOTfNyGzfd7ONfDzaG1CgqSyGYaXfH9dXnsoHqvD+56qk95f8YwMkLVMUZLhiKU5M57HV3/s2fjRQbm7V2Xec96b24jh8vKtPSYU8jNP+3tUNFm2Eybd+rd7MulQS1jcx68bodG8SCO34DCR+twk0FKtvkTPRINKBGkWbnU9/QKrP4KHi5nBF8EYFYtyBFtQlStwFuk5C+5YJYQvcOqG4+qqdjG7WNrDDLnbx7Pq30qMCC6QYn2bRD2hqOIF3m/olCaE5mDLS3aGN2zDc9jRGf49Lj7qTVm9XBG+mkZNl4RGjCn/y8Z6tNfCxxs2guUxega4+SSFmQF3HSJlJBohxZidT4lBmlovr5OKIncCM3Rl2IKjhYxAOuFVs+209zQBKVGJihDukCxtWO+fCzLDlDll2eOUVwUXNjm4BIRw2h5kIne/5yLhAhvoy2Lny0NJpktAEP8J58Y+42p9S6IfZkiZfYZP+RwICOQRxdRptme/+TPu70HYeHJR+azBgTRGU=
deploy:
  provider: pypi
  user: thesoulshell
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.6
  password:
    secure: n8kMnDnqYxAdrGhK2cORORQd7opNeFAhgw8iSKdzcsj60nANinKXLmMc5PgMXHm0IwWZcOJMjc663XHr8OmyqHydrdasxbttRkwBPqA9Uo3bIsb1A82vnElY0PFwzNPkrKt4qYGFUCyilrChg+LmwHzB1K1iTS5sFFbeTrcJjx1RFAAxQmCe/PCpcDsbN8Rv5S16SMIJpxAjbPscBveq9qXDPJnoLVy0LpzKCdJXGSREWIoDz0QuPOu+EDTim1jYScdqZJrA66oiyO6I2TPgk9Xmwv3NY9zKd6xZpwWkJIdBPLbV9GO3jRLwdmQZXZQ9psnrze8ajLzdEjbybE+CMaoLBkrE40pXChXVdCYEIz+FmyoxqTl25VNHQjKLY9BbC4LwT8t4mruIubBE95Dw4YeayYmqClgSmMQeXkBVvX6eRWKj+sEflkk6P1D7fhBQW3yJVTIy6zD6R3Dy0oNTrP3EiQUkvxBnjZMUzNIwqoyd2nkG3GpCbwkfl63akMdreGs6/01z3uo6dqgPDKlC53guoN8Cb0aPidz6Qr8PQxxk2G1xnkgetjirYdzuywivQTYAm8Pd8kWD7nTy7JgSV3LtMbIfMsEiunxjwqRT0xkUefEgl+4yMEOZY4CKinI+VLIBxeNtY1bHgDISkv1RqUf6GQVJuiXdhjqkF8b9YIc=
