language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python test/tests.py
notifications:
  slack:
    secure: HQnlkzjvqTICI6Lm680nbcwxAPCFd2ptkmvjPqzS/2fNaL6IpmsYZCJ9BmVH4tLdFovNWhMPj549lq78lOrIOgATkFRhiBuKhVgwpTrL12zEJ5s6rxqHhcQUnrUu/84uyD4/Wa3xXtqb7yOX+CyZRMPJA5mukI5sB/mvnas6DcjOTfNyGzfd7ONfDzaG1CgqSyGYaXfH9dXnsoHqvD+56qk95f8YwMkLVMUZLhiKU5M57HV3/s2fjRQbm7V2Xec96b24jh8vKtPSYU8jNP+3tUNFm2Eybd+rd7MulQS1jcx68bodG8SCO34DCR+twk0FKtvkTPRINKBGkWbnU9/QKrP4KHi5nBF8EYFYtyBFtQlStwFuk5C+5YJYQvcOqG4+qqdjG7WNrDDLnbx7Pq30qMCC6QYn2bRD2hqOIF3m/olCaE5mDLS3aGN2zDc9jRGf49Lj7qTVm9XBG+mkZNl4RGjCn/y8Z6tNfCxxs2guUxega4+SSFmQF3HSJlJBohxZidT4lBmlovr5OKIncCM3Rl2IKjhYxAOuFVs+209zQBKVGJihDukCxtWO+fCzLDlDll2eOUVwUXNjm4BIRw2h5kIne/5yLhAhvoy2Lny0NJpktAEP8J58Y+42p9S6IfZkiZfYZP+RwICOQRxdRptme/+TPu70HYeHJR+azBgTRGU=
deploy:
  provider: pypi
  user: thesoulshell
  distributions: sdist bdist_wheel
  password:
    secure: f7AVmXLteQXbAlyh3f90RlsM66fusOvoa1VgsHcMP9E8quZSXJlDMRcGhBZ0Jb3SBn+ypL8e0QAFU4uEDAe6J/0xgLmQgTzx0RqXp8lqnJ0IkCSs887Z6XikeLGzl9vmZRD/Yld2iB00Xnzr/gqTl+ZY5P0BPjSr0Vtzt8VMIo58SzXldcKRiX9fEEDLS/q22n+a/OCsqiBsAnXkFkh6sRbh4ikEy7im9q/ciNTxS+F6vlR8c+TkDyWVr5lcQ2R1lZb8nLcKfNuG4g2104jRDxC5hDGuEf/aP3NNxjpvjOAZRCz2Uxu4Z1Cgl4Sn5SFHfPDpEgYYfxwUoCU2Uu80cFSLTxrptgXDWUbyo3ffHmEDN3JcL+TAWDFfPUcNKQwJhwYhq4SrW71BY73a/aLtcvVFYMO01G+NePXMbHcZ/3Bc/lLx7aZMh4U6INQP0bRGJnoBB6trK+DY0KLz5G45SNEZhd9q14y1pA5/ASKIeUtRZmvDIVJ6dI2wD+fS4NsKtlgDvbQGaQt2ti/nmRSWr/h0BbLdf5r9xmw74zStR+q8pJq29XtSowPDOHNquekYcm6Mzefcsbuft46inHRJQtYlD03TODRjuxetMZOb7gQjcCv4bTnwr7nc/doiyUv0pBPLuv238TjXshQeriMrarSbrX6b0YdbEj5WqaJpSsE=
  on:
    branch: release
